// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Request
	Authentication
	Message
	MessageListReq
	Response
	MessageList
	Error
	JoinRequest
	JoinResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type Request_Type int32

const (
	Request_Authentication  Request_Type = 0
	Request_Message         Request_Type = 1
	Request_MessagesListReq Request_Type = 2
)

var Request_Type_name = map[int32]string{
	0: "Authentication",
	1: "Message",
	2: "MessagesListReq",
}
var Request_Type_value = map[string]int32{
	"Authentication":  0,
	"Message":         1,
	"MessagesListReq": 2,
}

func (x Request_Type) Enum() *Request_Type {
	p := new(Request_Type)
	*p = x
	return p
}
func (x Request_Type) String() string {
	return proto1.EnumName(Request_Type_name, int32(x))
}
func (x *Request_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Request_Type_value, data, "Request_Type")
	if err != nil {
		return err
	}
	*x = Request_Type(value)
	return nil
}

type Response_Type int32

const (
	Response_Message     Response_Type = 1
	Response_MessageList Response_Type = 3
	Response_Error       Response_Type = 2
)

var Response_Type_name = map[int32]string{
	1: "Message",
	3: "MessageList",
	2: "Error",
}
var Response_Type_value = map[string]int32{
	"Message":     1,
	"MessageList": 3,
	"Error":       2,
}

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}
func (x Response_Type) String() string {
	return proto1.EnumName(Response_Type_name, int32(x))
}
func (x *Response_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Response_Type_value, data, "Response_Type")
	if err != nil {
		return err
	}
	*x = Response_Type(value)
	return nil
}

type Error_Type int32

const (
	Error_InvalidRequest        Error_Type = 1
	Error_MustAuthenticateFirst Error_Type = 2
	Error_AlreadyAuthenticated  Error_Type = 3
	Error_UsernameTaken         Error_Type = 4
	Error_UserNotOnline         Error_Type = 5
)

var Error_Type_name = map[int32]string{
	1: "InvalidRequest",
	2: "MustAuthenticateFirst",
	3: "AlreadyAuthenticated",
	4: "UsernameTaken",
	5: "UserNotOnline",
}
var Error_Type_value = map[string]int32{
	"InvalidRequest":        1,
	"MustAuthenticateFirst": 2,
	"AlreadyAuthenticated":  3,
	"UsernameTaken":         4,
	"UserNotOnline":         5,
}

func (x Error_Type) Enum() *Error_Type {
	p := new(Error_Type)
	*p = x
	return p
}
func (x Error_Type) String() string {
	return proto1.EnumName(Error_Type_name, int32(x))
}
func (x *Error_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Error_Type_value, data, "Error_Type")
	if err != nil {
		return err
	}
	*x = Error_Type(value)
	return nil
}

type Request struct {
	Type             *Request_Type   `protobuf:"varint,1,req,name=type,enum=proto.Request_Type" json:"type,omitempty"`
	Authentication   *Authentication `protobuf:"bytes,2,opt,name=authentication" json:"authentication,omitempty"`
	Message          *Message        `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	MessageListReq   *MessageListReq `protobuf:"bytes,4,opt,name=message_list_req" json:"message_list_req,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetType() Request_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Request_Authentication
}

func (m *Request) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *Request) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Request) GetMessageListReq() *MessageListReq {
	if m != nil {
		return m.MessageListReq
	}
	return nil
}

type Authentication struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return proto1.CompactTextString(m) }
func (*Authentication) ProtoMessage()    {}

func (m *Authentication) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Message struct {
	Sender           *string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Recipient        *string `protobuf:"bytes,2,opt,name=recipient" json:"recipient,omitempty"`
	Content          *string `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *Message) GetRecipient() string {
	if m != nil && m.Recipient != nil {
		return *m.Recipient
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type MessageListReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MessageListReq) Reset()         { *m = MessageListReq{} }
func (m *MessageListReq) String() string { return proto1.CompactTextString(m) }
func (*MessageListReq) ProtoMessage()    {}

type Response struct {
	Type             *Response_Type `protobuf:"varint,1,req,name=type,enum=proto.Response_Type" json:"type,omitempty"`
	Message          *Message       `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	MessageList      *MessageList   `protobuf:"bytes,3,opt,name=message_list" json:"message_list,omitempty"`
	Error            *Error         `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetType() Response_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Response_Message
}

func (m *Response) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetMessageList() *MessageList {
	if m != nil {
		return m.MessageList
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageList struct {
	Messages         []*Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto1.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}

func (m *MessageList) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Error struct {
	Type             *Error_Type `protobuf:"varint,1,req,name=type,enum=proto.Error_Type" json:"type,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto1.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetType() Error_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Error_InvalidRequest
}

type JoinRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto1.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}

type JoinResponse struct {
	ServerAddress    *string `protobuf:"bytes,1,req,name=server_address" json:"server_address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto1.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}

func (m *JoinResponse) GetServerAddress() string {
	if m != nil && m.ServerAddress != nil {
		return *m.ServerAddress
	}
	return ""
}

func init() {
	proto1.RegisterEnum("proto.Request_Type", Request_Type_name, Request_Type_value)
	proto1.RegisterEnum("proto.Response_Type", Response_Type_name, Response_Type_value)
	proto1.RegisterEnum("proto.Error_Type", Error_Type_name, Error_Type_value)
}
